### ISSUE TITLE
Documentation / help not sufficient

### ISSUE THREAD

**Issue by Sogolumbo** [72nd/osc-utility#2]
Thanks for publishing this tool. I find it hard to use because some documentation seems to be missing.
The `--help` option and the readme file don't have enough information to use the tool properly. E.g. the flags for the send command aren't listed.

Please add the flags to the `--help` section or list them in the readme.
If you don't have time for that at least add a note to the readme that the flags can be found in the `main.go` file so others will know where to look for them.

**Comment by Sogolumbo** [comment]
The command `osc-utility message --help` returns an error:
```
> ./osc-utility message --help
message flag redefined: int
panic: message flag redefined: int

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000644e0, 0x6c0e80, 0xc0000512c0, 0xc000016988, 0x3, 0x686d58, 0x37)
        /usr/local/go/src/flag/flag.go:851 +0x485
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:754
flag.(*FlagSet).String(0xc0000644e0, 0xc000016988, 0x3, 0x0, 0x0, 0x686d58, 0x37, 0xc0000512b0)
        /usr/local/go/src/flag/flag.go:767 +0xa5
github.com/urfave/cli/v2.(*StringFlag).Apply(0xc00010cc80, 0xc0000644e0, 0x0, 0x0)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/flag_string.go:70 +0x1e5
github.com/urfave/cli/v2.flagSet(0x6791e7, 0x7, 0xc000174000, 0x8, 0xe, 0x70, 0xc000174000, 0x10)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/flag.go:125 +0x93
github.com/urfave/cli/v2.(*Command).newFlagSet(...)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:172
github.com/urfave/cli/v2.(*Command).parseFlags(0xc000166000, 0x6c4200, 0xc00000e7a0, 0x0, 0x8, 0xc000174000, 0x7)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:180 +0x65
github.com/urfave/cli/v2.(*Command).Run(0xc000166000, 0xc000062440, 0x0, 0x0)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:106 +0x105
github.com/urfave/cli/v2.(*App).RunContext(0xc00007ad00, 0x6c3720, 0xc0000160d8, 0xc000012090, 0x3, 0x3, 0x0, 0x0)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /home/irvin/.local/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/irvin/repos/osc-utility/main.go:92 +0xa32
        ```

**Comment by Sogolumbo** [comment]
I think this is caused by the same issue as #1.

**Comment by 72nd** [comment]
Yes exactly, this was related to Issue #1. The bug has been fixed with v0.2.0 and therefore the help should now be displayed correctly with the `--help` flag.
